/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AIAccessRule {
  'id' : string,
  'organizationId' : string,
  'active' : boolean,
  'grantedAt' : bigint,
  'grantedBy' : string,
  'providerId' : string,
  'grantedToType' : AIAccessRuleTarget,
}
export type AIAccessRuleTarget = { 'ByRole' : string } |
  { 'SpecificUser' : string } |
  { 'AllUsers' : null } |
  { 'ByDepartment' : string };
export type AIAuditAction = { 'ChatMessage' : null } |
  { 'ProviderAdded' : null } |
  { 'SharingRevoked' : null } |
  { 'ProviderDeleted' : null } |
  { 'ApiKeyUpdated' : null } |
  { 'SharingGranted' : null } |
  { 'ProviderDisabled' : null } |
  { 'ProviderEnabled' : null } |
  { 'TestAttempt' : null } |
  { 'ProviderUpdated' : null };
export interface AIAuditEntry {
  'id' : string,
  'organizationId' : string,
  'action' : AIAuditAction,
  'userId' : string,
  'timestamp' : bigint,
  'details' : string,
  'providerId' : [] | [string],
}
export interface AIProvider {
  'id' : string,
  'status' : AIProviderStatus,
  'name' : string,
  'createdAt' : bigint,
  'createdBy' : string,
  'isShared' : boolean,
  'workspaceId' : string,
  'providerType' : AIProviderType,
}
export interface AIProviderConfig {
  'region' : [] | [string],
  'orgId' : [] | [string],
  'temperature' : number,
  'timeoutSecs' : bigint,
  'deploymentName' : [] | [string],
  'endpointUrl' : [] | [string],
  'modelName' : [] | [string],
  'maxTokens' : bigint,
  'providerId' : string,
  'maskedApiKey' : [] | [string],
}
export type AIProviderStatus = { 'Active' : null } |
  { 'Disabled' : null } |
  { 'Testing' : null };
export type AIProviderType = { 'Mistral' : null } |
  { 'OpenAI' : null } |
  { 'Native' : null } |
  { 'AnthropicClaude' : null } |
  { 'GoogleGemini' : null } |
  { 'LocalLLM' : null } |
  { 'AzureOpenAI' : null } |
  { 'CustomEndpoint' : null };
export interface Account {
  'id' : string,
  'status' : AccountStatus,
  'reassignmentLog' : Array<AccountReassignmentEntry>,
  'licenceQuantity' : bigint,
  'distributorIds' : Array<string>,
  'estimatedRenewalValue' : number,
  'createdAt' : bigint,
  'contractType' : string,
  'productList' : Array<string>,
  'sites' : Array<AccountSite>,
  'updatedAt' : bigint,
  'vendorOwnerId' : string,
  'accountName' : string,
  'resellerOwnerId' : string,
  'customerIdNumber' : [] | [string],
  'customerDomain' : string,
  'renewalDate' : bigint,
}
export interface AccountInput {
  'status' : AccountStatus,
  'licenceQuantity' : bigint,
  'distributorIds' : Array<string>,
  'estimatedRenewalValue' : number,
  'contractType' : string,
  'productList' : Array<string>,
  'sites' : Array<AccountSite>,
  'vendorOwnerId' : string,
  'accountName' : string,
  'resellerOwnerId' : string,
  'customerIdNumber' : [] | [string],
  'customerDomain' : string,
  'renewalDate' : bigint,
}
export interface AccountLayout {
  'id' : LayoutId,
  'visibilityRules' : Array<VisibilityRule__1>,
  'name' : string,
  'createdAt' : bigint,
  'createdBy' : string,
  'tabs' : Array<AccountTab>,
  'description' : string,
  'version' : bigint,
  'fields' : Array<LayoutField>,
  'updatedAt' : bigint,
  'isDefault' : boolean,
  'sections' : Array<LayoutSection>,
}
export interface AccountReassignmentEntry {
  'previousOwnerId' : string,
  'changedAt' : bigint,
  'changedBy' : string,
  'ownerType' : OwnerType,
  'newOwnerId' : string,
  'entryId' : string,
  'approvalStatus' : ReassignmentApprovalStatus,
  'reason' : string,
}
export interface AccountSite {
  'region' : string,
  'country' : string,
  'distributorId' : [] | [string],
  'siteName' : string,
  'productLines' : Array<string>,
  'resellerId' : [] | [string],
  'siteId' : string,
}
export type AccountStatus = { 'Churned' : null } |
  { 'Prospect' : null } |
  { 'Active' : null } |
  { 'AtRisk' : null };
export interface AccountTab {
  'id' : string,
  'sortOrder' : bigint,
  'isCustom' : boolean,
  'isVisible' : boolean,
  'tabLabel' : string,
  'hiddenForDepts' : Array<string>,
  'hiddenForRoles' : Array<string>,
}
export type ActivationStatus = { 'Active' : null } |
  { 'Suspended' : null } |
  { 'Pending' : null };
export interface ActiveResetTokenView {
  'userEmail' : string,
  'expiresAt' : bigint,
  'userId' : string,
  'tokenPrefix' : string,
  'createdAt' : bigint,
}
export type ActivityStatus = { 'Overdue' : null } |
  { 'InProgress' : null } |
  { 'Completed' : null } |
  { 'Pending' : null };
export interface Alert {
  'id' : string,
  'alertType' : AlertType,
  'accountId' : [] | [string],
  'userId' : string,
  'createdAt' : bigint,
  'isRead' : boolean,
  'message' : string,
  'severity' : AlertSeverity,
}
export type AlertDeliveryMode = { 'DashboardOnly' : null } |
  { 'Both' : null } |
  { 'MessageOnly' : null };
export type AlertFrequency = { 'Hourly' : null } |
  { 'Weekly' : null } |
  { 'Daily' : null } |
  { 'Realtime' : null };
export interface AlertInput {
  'alertType' : AlertType,
  'accountId' : [] | [string],
  'userId' : string,
  'message' : string,
  'severity' : AlertSeverity,
}
export type AlertSeverity = { 'Low' : null } |
  { 'High' : null } |
  { 'Medium' : null };
export type AlertType = { 'MissingContact' : null } |
  { 'DealExpiry' : null } |
  { 'RenewalDue' : null } |
  { 'BusinessPlanDue' : null } |
  { 'PromoExpiry' : null } |
  { 'CustomerRisk' : null } |
  { 'DuplicateAccount' : null } |
  { 'LeadToCall' : null };
export interface AuditEntry {
  'id' : string,
  'action' : string,
  'userId' : string,
  'entityId' : string,
  'timestamp' : bigint,
  'details' : string,
  'entityType' : string,
}
export type AuthError = { 'SessionInvalid' : null } |
  { 'TokenAlreadyUsed' : null } |
  { 'CompanyNotFound' : null } |
  { 'NotAuthorized' : null } |
  { 'PasswordReused' : null } |
  { 'MfaNotEnrolled' : null } |
  { 'TokenExpired' : null } |
  { 'InvalidCredentials' : null } |
  { 'TokenInvalid' : null } |
  { 'AccountLocked' : { 'lockedUntil' : bigint } } |
  { 'ConfigError' : string } |
  { 'MfaInvalidCode' : null } |
  { 'MfaAlreadyEnrolled' : null } |
  { 'MfaRequired' : null } |
  { 'PasswordAuthDisabled' : null } |
  { 'PasswordTooWeak' : Array<string> } |
  { 'SessionExpired' : null } |
  { 'UserNotFound' : null } |
  { 'AccountInactive' : null };
export interface AuthSettings {
  'passwordMaxLength' : bigint,
  'passwordLoginEnabled' : boolean,
  'lockoutDurationMinutes' : bigint,
  'mfaGracePeriodDays' : bigint,
  'mfaRequiredForAll' : boolean,
  'passwordMinLength' : bigint,
  'orgId' : string,
  'ssoEnabled' : boolean,
  'passwordComplexityRequired' : boolean,
  'internetIdentityEnabled' : boolean,
  'mfaOptionalEnrollment' : boolean,
  'sessionTimeoutMinutes' : bigint,
  'maxFailedAttempts' : bigint,
  'mfaRequiredForAdmins' : boolean,
  'passwordExpiryDays' : bigint,
  'lockoutEnabled' : boolean,
  'passwordReusePreventCount' : bigint,
  'permanentLockUntilReset' : boolean,
  'mfaEnabled' : boolean,
}
export interface BulkImportResult {
  'created' : bigint,
  'skipped' : bigint,
  'errors' : Array<string>,
}
export interface BusinessPlan {
  'id' : string,
  'month' : [] | [bigint],
  'revenueTarget' : number,
  'objective' : string,
  'quarter' : [] | [bigint],
  'createdAt' : bigint,
  'year' : bigint,
  'activities' : Array<BusinessPlanActivity>,
  'partnerId' : string,
  'vendorOwnerId' : string,
  'pipelineTarget' : number,
  'planType' : PlanType,
}
export interface BusinessPlanActivity {
  'id' : string,
  'status' : ActivityStatus,
  'owner' : string,
  'dueDate' : bigint,
  'description' : string,
  'notes' : string,
}
export interface BusinessPlanInput {
  'month' : [] | [bigint],
  'revenueTarget' : number,
  'objective' : string,
  'quarter' : [] | [bigint],
  'year' : bigint,
  'activities' : Array<BusinessPlanActivity>,
  'partnerId' : string,
  'vendorOwnerId' : string,
  'pipelineTarget' : number,
  'planType' : PlanType,
}
export interface ChatMessage {
  'id' : string,
  'content' : string,
  'context' : [] | [string],
  'aiSource' : string,
  'role' : ChatRole,
  'timestamp' : bigint,
  'suggestedActions' : Array<string>,
}
export type ChatRole = { 'System' : null } |
  { 'User' : null } |
  { 'Assistant' : null };
export interface CompanyProfile {
  'id' : string,
  'emailDomain' : string,
  'partnerDomains' : Array<string>,
  'setupComplete' : boolean,
  'createdAt' : bigint,
  'claimedAt' : [] | [bigint],
  'claimedBy' : [] | [string],
  'logoKey' : [] | [string],
  'activationStatus' : ActivationStatus,
  'vendorId' : [] | [string],
  'companyName' : string,
  'companyType' : CompanyType,
  'companyId' : string,
}
export interface CompanyProfileInput {
  'emailDomain' : string,
  'partnerDomains' : Array<string>,
  'logoKey' : [] | [string],
  'companyName' : string,
  'companyType' : CompanyType,
  'companyId' : string,
}
export type CompanyType = { 'Distributor' : null } |
  { 'Reseller' : null } |
  { 'Vendor' : null };
export type ConditionOperator = { 'contains' : null } |
  { 'notEquals' : null } |
  { 'equals' : null };
export interface Contact {
  'id' : string,
  'contactType' : string,
  'lastContactedDate' : [] | [bigint],
  'accountId' : string,
  'createdAt' : bigint,
  'email' : string,
  'contactOwner' : string,
  'jobTitle' : string,
  'notes' : string,
  'nextActionDate' : [] | [bigint],
  'phone' : string,
  'lastName' : string,
  'firstName' : string,
}
export interface ContactInput {
  'contactType' : string,
  'lastContactedDate' : [] | [bigint],
  'accountId' : string,
  'email' : string,
  'contactOwner' : string,
  'jobTitle' : string,
  'notes' : string,
  'nextActionDate' : [] | [bigint],
  'phone' : string,
  'lastName' : string,
  'firstName' : string,
}
export interface Conversation {
  'id' : ConversationId,
  'lastMessageAt' : bigint,
  'lastMessagePreview' : string,
  'createdAt' : bigint,
  'relatedEntityId' : [] | [string],
  'participantIds' : Array<string>,
  'conversationType' : ConversationType,
}
export type ConversationId = string;
export interface ConversationThread {
  'messages' : Array<Message>,
  'conversation' : Conversation,
}
export type ConversationType = { 'DealThread' : null } |
  { 'RenewalThread' : null } |
  { 'DirectMessage' : null } |
  { 'GroupMessage' : null } |
  { 'AccountThread' : null };
export interface CreditBalance {
  'storageCredits' : bigint,
  'aiCredits' : bigint,
  'computeCredits' : bigint,
}
export interface CreditPackage {
  'id' : string,
  'storageCredits' : bigint,
  'pricingGBP' : number,
  'aiCredits' : bigint,
  'name' : string,
  'description' : string,
  'computeCredits' : bigint,
}
export interface CreditTopUp {
  'simulatedAmount' : number,
  'userId' : string,
  'aiAdded' : bigint,
  'computeAdded' : bigint,
  'timestamp' : bigint,
  'storageAdded' : bigint,
  'packageId' : string,
}
export type Currency = { 'AUD' : null } |
  { 'BTC' : null } |
  { 'CNY' : null } |
  { 'EUR' : null } |
  { 'GBP' : null } |
  { 'JPY' : null } |
  { 'USD' : null };
export interface CurrentQuarterResult {
  'daysElapsed' : bigint,
  'quarterDef' : QuarterDef,
  'progressPercent' : number,
  'daysRemaining' : bigint,
}
export interface CustomFieldBulkValidationResult {
  'allValid' : boolean,
  'results' : Array<CustomFieldValidationResult>,
}
export interface CustomFieldDef {
  'id' : string,
  'lockedByVendor' : boolean,
  'editPermissions' : Array<CustomFieldPermission>,
  'isRequired' : boolean,
  'isExportVisible' : boolean,
  'fieldLabel' : string,
  'createdAt' : bigint,
  'createdBy' : string,
  'allowedValues' : Array<string>,
  'isSearchable' : boolean,
  'isReportable' : boolean,
  'isArchived' : boolean,
  'updatedAt' : bigint,
  'viewPermissions' : Array<CustomFieldPermission>,
  'validationRules' : Array<CustomFieldValidationRule>,
  'fieldDescription' : string,
  'visibilityScope' : CustomFieldVisibilityScope,
  'objectType' : CustomFieldObjectType,
  'isApiVisible' : boolean,
  'fieldName' : string,
  'fieldType' : CustomFieldType,
  'defaultValue' : [] | [string],
}
export interface CustomFieldDefInput {
  'editPermissions' : Array<CustomFieldPermission>,
  'isRequired' : boolean,
  'isExportVisible' : boolean,
  'fieldLabel' : string,
  'allowedValues' : Array<string>,
  'isSearchable' : boolean,
  'isReportable' : boolean,
  'viewPermissions' : Array<CustomFieldPermission>,
  'validationRules' : Array<CustomFieldValidationRule>,
  'fieldDescription' : string,
  'visibilityScope' : CustomFieldVisibilityScope,
  'objectType' : CustomFieldObjectType,
  'isApiVisible' : boolean,
  'fieldName' : string,
  'fieldType' : CustomFieldType,
  'defaultValue' : [] | [string],
}
export type CustomFieldObjectType = { 'distributorProfile' : null } |
  { 'mdfRequest' : null } |
  { 'businessPlan' : null } |
  { 'marketingActivity' : null } |
  { 'resellerProfile' : null } |
  { 'promotion' : null } |
  { 'customerAccount' : null } |
  { 'opportunity' : null } |
  { 'userProfile' : null } |
  { 'dealRegistration' : null };
export type CustomFieldPermission = { 'creator' : null } |
  { 'owner' : null } |
  { 'edit' : null } |
  { 'view' : null };
export type CustomFieldType = { 'tag' : null } |
  { 'url' : null } |
  { 'regionSelector' : null } |
  { 'date' : null } |
  { 'userSelector' : null } |
  { 'text' : null } |
  { 'multiSelect' : null } |
  { 'email' : null } |
  { 'currency' : null } |
  { 'number' : null } |
  { 'longText' : null } |
  { 'checkbox' : null } |
  { 'organizationSelector' : null } |
  { 'phoneNumber' : null } |
  { 'attachment' : null } |
  { 'percentage' : null } |
  { 'datetime' : null } |
  { 'dropdown' : null };
export interface CustomFieldValidationResult {
  'errorMessage' : [] | [string],
  'fieldDefId' : string,
  'isValid' : boolean,
}
export interface CustomFieldValidationRule {
  'ruleType' : CustomFieldValidationRuleType,
  'ruleValue' : string,
}
export type CustomFieldValidationRuleType = { 'minValue' : null } |
  { 'conditionalRequired' : null } |
  { 'allowedValues' : null } |
  { 'unique' : null } |
  { 'required' : null } |
  { 'maxLength' : null } |
  { 'maxValue' : null } |
  { 'regex' : null } |
  { 'minLength' : null };
export interface CustomFieldValue {
  'value' : string,
  'createdAt' : bigint,
  'uploadedFileKeys' : Array<string>,
  'updatedAt' : bigint,
  'updatedBy' : string,
  'objectId' : string,
  'fieldDefId' : string,
  'objectType' : CustomFieldObjectType,
}
export interface CustomFieldValueInput {
  'value' : string,
  'uploadedFileKeys' : Array<string>,
  'objectId' : string,
  'fieldDefId' : string,
  'objectType' : CustomFieldObjectType,
}
export interface CustomFieldValueRef { 'value' : string, 'fieldDefId' : string }
export type CustomFieldVisibilityScope = { 'internalOnly' : null } |
  { 'allOrgs' : null } |
  { 'distributorOnly' : null } |
  { 'resellerOnly' : null } |
  { 'roleSpecific' : null } |
  { 'vendorOnly' : null };
export type CustomerIdAuditAction = { 'created' : null } |
  { 'formatRuleChanged' : null } |
  { 'duplicateBlocked' : null } |
  { 'manualOverride' : null } |
  { 'mergeResolved' : null } |
  { 'updated' : null };
export interface CustomerIdAuditEntry {
  'action' : CustomerIdAuditAction,
  'accountId' : string,
  'detail' : string,
  'entryId' : string,
  'performedAt' : bigint,
  'performedBy' : string,
  'customerId' : string,
}
export interface CustomerIdFormatRule {
  'duplicatePreventionEnabled' : boolean,
  'regionRules' : Array<string>,
  'autoGenerationEnabled' : boolean,
  'formatPattern' : string,
  'characterLimit' : bigint,
  'numberSequencing' : CustomerIdNumberSequencing,
  'updatedAt' : bigint,
  'manualOverridePermitted' : boolean,
  'prefixRules' : string,
  'vendorId' : string,
  'allowedSeparators' : Array<string>,
  'lastSequenceNumber' : bigint,
}
export interface CustomerIdFormatRuleInput {
  'duplicatePreventionEnabled' : boolean,
  'regionRules' : Array<string>,
  'autoGenerationEnabled' : boolean,
  'formatPattern' : string,
  'characterLimit' : bigint,
  'numberSequencing' : CustomerIdNumberSequencing,
  'manualOverridePermitted' : boolean,
  'prefixRules' : string,
  'allowedSeparators' : Array<string>,
}
export interface CustomerIdGenerateRequest {
  'vendorId' : string,
  'manualInput' : [] | [string],
  'regionCode' : [] | [string],
}
export type CustomerIdNumberSequencing = { 'custom' : null } |
  { 'random' : null } |
  { 'sequential' : null };
export interface CustomerIdValidationResult {
  'formattedId' : [] | [string],
  'errorMessage' : [] | [string],
  'isDuplicate' : boolean,
  'isValid' : boolean,
}
export interface DashboardLayout {
  'id' : string,
  'assignedTo' : Array<string>,
  'isTemplate' : boolean,
  'widgets' : Array<WidgetConfig>,
  'name' : string,
  'createdAt' : bigint,
  'createdBy' : string,
  'description' : string,
  'templateType' : [] | [DashboardTemplateType],
  'updatedAt' : bigint,
}
export type DashboardTemplateType = { 'Role' : null } |
  { 'Department' : null } |
  { 'OrgType' : null };
export interface DealRegistration {
  'id' : string,
  'submittedDate' : [] | [bigint],
  'status' : DealStatus,
  'closeDate' : bigint,
  'accountId' : string,
  'createdAt' : bigint,
  'submittedBy' : string,
  'updatedAt' : bigint,
  'vendorOwnerId' : string,
  'resellerId' : string,
  'opportunityName' : string,
  'notes' : string,
  'estimatedValue' : number,
  'quantity' : bigint,
  'customerDomain' : string,
  'competitor' : string,
  'product' : string,
  'dealStage' : string,
}
export interface DealRegistrationInput {
  'submittedDate' : [] | [bigint],
  'status' : DealStatus,
  'closeDate' : bigint,
  'accountId' : string,
  'submittedBy' : string,
  'vendorOwnerId' : string,
  'resellerId' : string,
  'opportunityName' : string,
  'notes' : string,
  'estimatedValue' : number,
  'quantity' : bigint,
  'customerDomain' : string,
  'competitor' : string,
  'product' : string,
  'dealStage' : string,
}
export type DealStatus = { 'Won' : null } |
  { 'UnderReview' : null } |
  { 'Lost' : null } |
  { 'Approved' : null } |
  { 'Draft' : null } |
  { 'Rejected' : null } |
  { 'Submitted' : null } |
  { 'Expired' : null };
export interface DistributorInput {
  'emailDomain' : string,
  'primaryAdminEmail' : string,
  'logoKey' : [] | [string],
  'companyName' : string,
  'companyId' : string,
}
export interface DistributorProfile {
  'id' : string,
  'emailDomain' : string,
  'setupComplete' : boolean,
  'primaryAdminEmail' : string,
  'createdAt' : bigint,
  'updatedAt' : bigint,
  'logoKey' : [] | [string],
  'activationStatus' : ActivationStatus,
  'companyName' : string,
  'resellerIds' : Array<string>,
  'vendorIds' : Array<string>,
  'companyId' : string,
}
export interface DuplicateCheckResult {
  'matchType' : string,
  'matchingDomain' : [] | [string],
  'suggestion' : string,
  'existingOwner' : [] | [string],
  'isDuplicate' : boolean,
  'existingAccountId' : [] | [string],
}
export interface DuplicateDRRecord {
  'id' : string,
  'status' : DuplicateDRStatus,
  'accountId' : string,
  'submittedAt' : bigint,
  'reviewNote' : [] | [string],
  'existingDRId' : string,
  'reviewedAt' : [] | [bigint],
  'reviewedBy' : [] | [Principal],
  'reviewAction' : [] | [string],
  'resellerId' : string,
  'existingResellerId' : string,
  'product' : string,
  'newDRId' : string,
}
export type DuplicateDRStatus = { 'Merged' : null } |
  { 'PendingVendorReview' : null } |
  { 'Approved' : null } |
  { 'Rejected' : null } |
  { 'Escalated' : null } |
  { 'Reassigned' : null };
export interface EngagementGapAlert {
  'threshold' : bigint,
  'detectedAt' : Timestamp,
  'alertLevel' : RiskTier,
  'description' : string,
  'daysSinceEngagement' : bigint,
  'entityId' : string,
  'entityName' : string,
  'entityType' : string,
}
export interface ExchangeRateSnapshot {
  'toCurrency' : Currency,
  'provider' : ForexProvider,
  'fetchedAt' : Timestamp,
  'fromCurrency' : Currency,
  'rate' : number,
}
export interface FailedLoginEvent {
  'id' : string,
  'userId' : [] | [string],
  'email' : string,
  'attemptCount' : bigint,
  'timestamp' : bigint,
  'ipHint' : string,
  'companyType' : CompanyType,
  'reason' : string,
}
export type FieldType = { 'Tag' : null } |
  { 'Url' : null } |
  { 'Email' : null } |
  { 'UserSelector' : null } |
  { 'Date' : null } |
  { 'Text' : null } |
  { 'MultiSelect' : null } |
  { 'Phone' : null } |
  { 'Currency' : null } |
  { 'LongText' : null } |
  { 'Checkbox' : null } |
  { 'DateTime' : null } |
  { 'RegionSelector' : null } |
  { 'OrgSelector' : null } |
  { 'Attachment' : null } |
  { 'Number' : null } |
  { 'Dropdown' : null } |
  { 'Percentage' : null };
export interface FiscalYearConfig {
  'fiscalYearType' : FiscalYearType,
  'updatedAt' : Timestamp,
  'updatedBy' : string,
  'vendorId' : string,
  'quarters' : Array<QuarterDef>,
}
export interface FiscalYearConfigInput {
  'fiscalYearType' : FiscalYearType,
  'quarters' : Array<QuarterDef>,
}
export type FiscalYearType = { 'CustomFiscal' : null } |
  { 'CalendarYear' : null };
export interface ForexConfig {
  'refreshMode' : ForexRefreshMode,
  'customApiEndpoint' : [] | [string],
  'updatedAt' : Timestamp,
  'updatedBy' : Principal,
  'primaryProvider' : ForexProvider,
  'defaultCurrency' : Currency,
  'fallbackProviders' : Array<ForexProvider>,
  'cryptoEnabled' : boolean,
}
export type ForexProvider = { 'XE' : null } |
  { 'ECB' : null } |
  { 'Binance' : null } |
  { 'BankOfEngland' : null } |
  { 'Coinbase' : null } |
  { 'CustomAPI' : null } |
  { 'OpenExchangeRates' : null };
export type ForexRefreshMode = { 'Hourly' : null } |
  { 'Weekly' : null } |
  { 'Daily' : null } |
  { 'LiveOnLoad' : null } |
  { 'ManualOnly' : null };
export interface ForgeAIAlertConfig {
  'alertType' : ForgeAIAlertType,
  'escalationRecipients' : Array<string>,
  'primaryAdminRecipient' : boolean,
  'endUsersRecipient' : boolean,
  'riskThreshold' : [] | [bigint],
  'lockStatus' : LockStatus,
  'secondaryAdminRecipient' : boolean,
  'deliveryMode' : AlertDeliveryMode,
  'enabled' : boolean,
  'frequency' : AlertFrequency,
}
export type ForgeAIAlertType = { 'BusinessPlanInactivity' : null } |
  { 'AccountRisk' : null } |
  { 'ResellerEngagementGap' : null } |
  { 'DealRegistrationWarning' : null } |
  { 'DistributorEngagementGap' : null } |
  { 'StalledApproval' : null } |
  { 'ChannelHealthScoreChange' : null } |
  { 'RenewalRisk' : null } |
  { 'PipelineHealth' : null };
export interface ForgeAIAuditEntry {
  'id' : string,
  'analysisType' : string,
  'triggeredBy' : string,
  'entityId' : string,
  'timestamp' : Timestamp,
  'details' : string,
  'entityName' : string,
  'confidence' : [] | [bigint],
  'riskLevel' : [] | [RiskTier],
}
export interface ForgeAIChatSession {
  'id' : string,
  'contextId' : [] | [string],
  'contextType' : [] | [string],
  'messages' : Array<ChatMessage>,
  'userId' : string,
  'createdAt' : bigint,
  'updatedAt' : bigint,
  'providerId' : string,
}
export interface ForgeAIRecommendation {
  'id' : string,
  'affectedEntityName' : string,
  'affectedEntityType' : string,
  'suggestedAction' : string,
  'recommendationType' : string,
  'affectedEntityId' : string,
  'summary' : string,
  'timestamp' : Timestamp,
  'confidence' : bigint,
  'dismissed' : boolean,
  'riskLevel' : RiskTier,
}
export interface ForgeAISettings {
  'distributorInactivityThresholdDays' : bigint,
  'recommendationsEnabled' : boolean,
  'resellerInactivityThresholdDays' : bigint,
  'engagementGapEnabled' : boolean,
  'escalationThresholdDays' : bigint,
  'gapNotificationConfig' : GapNotificationConfig,
  'auditLogLevel' : string,
  'enabled' : boolean,
  'messagingAssistEnabled' : boolean,
  'smartQueriesEnabled' : boolean,
  'warningThresholdDays' : bigint,
  'renewalRiskEnabled' : boolean,
}
export interface GapNotificationConfig {
  'high' : GapNotificationRecipientConfig,
  'critical' : GapNotificationRecipientConfig,
}
export interface GapNotificationRecipientConfig {
  'primaryAdmin' : boolean,
  'assignedDistributor' : boolean,
  'assignedReseller' : boolean,
  'accountOwner' : boolean,
}
export interface InAppNotification {
  'id' : string,
  'title' : string,
  'notificationType' : NotificationType,
  'createdAt' : Timestamp,
  'isRead' : boolean,
  'entityId' : [] | [string],
  'message' : string,
  'entityType' : [] | [string],
  'recipientId' : Principal,
}
export type InvitationStatus = { 'Accepted' : null } |
  { 'Cancelled' : null } |
  { 'Expired' : null } |
  { 'Pending' : null };
export interface InviteUserInput {
  'role' : UserRole,
  'email' : string,
  'companyId' : string,
}
export interface LayoutAuditEntry {
  'id' : string,
  'beforeState' : [] | [string],
  'action' : string,
  'entityId' : string,
  'performedBy' : string,
  'timestamp' : bigint,
  'entityType' : string,
  'afterState' : [] | [string],
}
export interface LayoutField {
  'id' : string,
  'fieldLabel' : string,
  'sortOrder' : bigint,
  'sectionId' : [] | [string],
  'visible' : boolean,
  'required' : boolean,
  'options' : Array<string>,
  'fieldType' : FieldType,
  'defaultValue' : [] | [string],
}
export type LayoutId = string;
export interface LayoutPermissions {
  'canManageDashboardTemplates' : boolean,
  'canManageCustomFields' : boolean,
  'canManageWidgets' : boolean,
  'canManageLayouts' : boolean,
}
export interface LayoutSection {
  'id' : string,
  'title' : string,
  'sortOrder' : bigint,
  'collapsible' : boolean,
  'fieldIds' : Array<string>,
}
export type LockSource = { 'Distributor' : null } |
  { 'Vendor' : null };
export type LockStatus = { 'Unlocked' : null } |
  { 'LockedBy' : LockSource } |
  { 'InheritedFrom' : LockSource };
export interface LockedAccountInfo {
  'failedCount' : bigint,
  'userId' : string,
  'fullName' : string,
  'email' : string,
  'lockedAt' : bigint,
  'lockedUntil' : bigint,
  'companyId' : string,
}
export interface MarketingActivity {
  'id' : string,
  'roi' : [] | [bigint],
  'status' : MarketingActivityStatus,
  'activityName' : string,
  'activityType' : MarketingActivityType,
  'endDate' : bigint,
  'associatedPromotionIds' : Array<string>,
  'customFieldValues' : Array<CustomFieldValueRef>,
  'createdAt' : bigint,
  'distributorId' : [] | [string],
  'ownerUserId' : string,
  'updatedAt' : bigint,
  'vendorOwnerId' : string,
  'resellerId' : [] | [string],
  'currency' : string,
  'targetAccountIds' : Array<string>,
  'budget' : bigint,
  'startDate' : bigint,
}
export interface MarketingActivityInput {
  'activityName' : string,
  'activityType' : MarketingActivityType,
  'endDate' : bigint,
  'associatedPromotionIds' : Array<string>,
  'distributorId' : [] | [string],
  'vendorOwnerId' : string,
  'resellerId' : [] | [string],
  'currency' : string,
  'targetAccountIds' : Array<string>,
  'budget' : bigint,
  'startDate' : bigint,
}
export type MarketingActivityStatus = { 'cancelled' : null } |
  { 'completed' : null } |
  { 'planned' : null } |
  { 'inProgress' : null };
export type MarketingActivityType = { 'sponsorship' : null } |
  { 'content' : null } |
  { 'other' : null } |
  { 'emailCampaign' : null } |
  { 'webinar' : null } |
  { 'event' : null };
export interface MarketingActivityUpdateInput {
  'roi' : [] | [bigint],
  'status' : [] | [MarketingActivityStatus],
  'activityName' : [] | [string],
  'activityType' : [] | [MarketingActivityType],
  'endDate' : [] | [bigint],
  'associatedPromotionIds' : [] | [Array<string>],
  'currency' : [] | [string],
  'targetAccountIds' : [] | [Array<string>],
  'budget' : [] | [bigint],
  'startDate' : [] | [bigint],
}
export interface MdfRequest {
  'id' : string,
  'status' : MdfRequestStatus,
  'requestorOrgId' : string,
  'customFieldValues' : Array<CustomFieldValueRef>,
  'approvedAt' : [] | [bigint],
  'approvedBy' : [] | [string],
  'createdAt' : bigint,
  'approvalNote' : [] | [string],
  'budgetYear' : bigint,
  'updatedAt' : bigint,
  'vendorOwnerId' : string,
  'requestorUserId' : string,
  'currency' : string,
  'budgetQuarter' : [] | [bigint],
  'associatedAccountId' : [] | [string],
  'amount' : bigint,
  'purpose' : string,
}
export interface MdfRequestDecisionInput {
  'decision' : MdfRequestStatus,
  'approvalNote' : [] | [string],
}
export interface MdfRequestInput {
  'budgetYear' : bigint,
  'vendorOwnerId' : string,
  'currency' : string,
  'budgetQuarter' : [] | [bigint],
  'associatedAccountId' : [] | [string],
  'amount' : bigint,
  'purpose' : string,
}
export type MdfRequestStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'paid' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Message {
  'id' : MessageId,
  'content' : string,
  'sentAt' : bigint,
  'conversationId' : ConversationId,
  'attachmentUrls' : Array<string>,
  'senderId' : string,
  'readBy' : Array<ReadReceipt>,
}
export type MessageId = string;
export interface MfaSetupChallenge {
  'totpSecret' : string,
  'qrCodeUrl' : string,
}
export interface NLQueryResult {
  'interpretationExplanation' : string,
  'queryResult' : SmartQueryResult,
  'confidenceLevel' : string,
  'interpretedFilters' : SmartQueryFilter,
  'originalQuery' : string,
  'interpretedQueryType' : SmartQueryType,
}
export interface NewsItem {
  'id' : string,
  'title' : string,
  'publishDate' : bigint,
  'body' : string,
  'createdAt' : bigint,
  'publishedBy' : string,
  'visibility' : NewsVisibility,
}
export interface NewsItemInput {
  'title' : string,
  'publishDate' : bigint,
  'body' : string,
  'visibility' : NewsVisibility,
}
export type NewsVisibility = { 'SpecificResellers' : Array<string> } |
  { 'SpecificRegions' : Array<string> } |
  { 'AllResellers' : null } |
  { 'VendorOnly' : null };
export interface Note {
  'id' : string,
  'content' : string,
  'accountId' : string,
  'authorId' : string,
  'createdAt' : bigint,
  'authorName' : string,
  'authorRole' : string,
  'updatedAt' : [] | [bigint],
  'editedBy' : [] | [string],
}
export interface NoteInput {
  'content' : string,
  'accountId' : string,
  'authorName' : string,
  'authorRole' : string,
}
export interface NotificationRule {
  'displayName' : string,
  'ruleId' : NotificationRuleId,
  'isEditable' : boolean,
  'lockStatus' : LockStatus,
  'currentValue' : boolean,
}
export type NotificationRuleId = string;
export type NotificationType = { 'TierAssigned' : null } |
  { 'WorkspaceActivated' : null } |
  { 'DealApproved' : null } |
  { 'DealRejected' : null } |
  { 'DuplicateDRFlagged' : null } |
  { 'DuplicateDRReviewed' : null } |
  { 'EngagementGapAlert' : null } |
  { 'UnlockRequested' : null };
export interface Opportunity {
  'id' : string,
  'status' : OpportunityStatus,
  'closeDate' : bigint,
  'customFieldValues' : Array<CustomFieldValueRef>,
  'createdAt' : bigint,
  'customerAccountId' : [] | [string],
  'distributorId' : [] | [string],
  'ownerUserId' : string,
  'associatedDealIds' : Array<string>,
  'updatedAt' : bigint,
  'stage' : OpportunityStage,
  'vendorOwnerId' : string,
  'resellerId' : [] | [string],
  'opportunityName' : string,
  'revenueEstimate' : bigint,
}
export interface OpportunityInput {
  'closeDate' : bigint,
  'customerAccountId' : [] | [string],
  'distributorId' : [] | [string],
  'associatedDealIds' : Array<string>,
  'stage' : OpportunityStage,
  'vendorOwnerId' : string,
  'resellerId' : [] | [string],
  'opportunityName' : string,
  'revenueEstimate' : bigint,
}
export type OpportunityStage = { 'prospecting' : null } |
  { 'closedWon' : null } |
  { 'proposal' : null } |
  { 'negotiation' : null } |
  { 'qualification' : null } |
  { 'closedLost' : null };
export type OpportunityStatus = { 'active' : null } |
  { 'archived' : null };
export interface OpportunityUpdateInput {
  'status' : [] | [OpportunityStatus],
  'closeDate' : [] | [bigint],
  'customerAccountId' : [] | [string],
  'distributorId' : [] | [string],
  'associatedDealIds' : [] | [Array<string>],
  'stage' : [] | [OpportunityStage],
  'resellerId' : [] | [string],
  'opportunityName' : [] | [string],
  'revenueEstimate' : [] | [bigint],
}
export interface OrgForgeAIAlertSettings {
  'orgId' : string,
  'canManageForgeAIAlertsSecondaryAdmins' : Array<Principal>,
  'alertConfigs' : Array<ForgeAIAlertConfig>,
}
export interface OrgVisibilityConfig {
  'orgId' : string,
  'lockedByParent' : boolean,
  'updatedAt' : bigint,
  'customRules' : Array<VisibilityRule>,
  'defaultInheritFromVendor' : boolean,
}
export interface OrgVisibilityConfigInput {
  'lockedByParent' : boolean,
  'defaultInheritFromVendor' : boolean,
}
export type OwnerType = { 'Distributor' : null } |
  { 'Reseller' : null } |
  { 'Vendor' : null };
export type PartnerTier = { 'Gold' : null } |
  { 'Platinum' : null } |
  { 'Silver' : null };
export interface PasswordResetToken {
  'id' : string,
  'expiresAt' : bigint,
  'userId' : string,
  'createdAt' : bigint,
  'used' : boolean,
  'email' : string,
  'companyType' : CompanyType,
  'revokedBy' : [] | [string],
}
export type PlanType = { 'Quarterly' : null } |
  { 'Monthly' : null } |
  { 'Annual' : null };
export interface PriceList {
  'id' : string,
  'region' : string,
  'expiryDate' : bigint,
  'productFamily' : string,
  'name' : string,
  'createdAt' : bigint,
  'createdBy' : string,
  'version' : string,
  'currency' : string,
  'effectiveDate' : bigint,
  'fileKey' : string,
}
export interface PriceListInput {
  'region' : string,
  'expiryDate' : bigint,
  'productFamily' : string,
  'name' : string,
  'version' : string,
  'currency' : string,
  'effectiveDate' : bigint,
  'fileKey' : string,
}
export type ProfileVisibilityScope = { 'ConnectedOnly' : null } |
  { 'WorkspaceOnly' : null };
export interface Promotion {
  'id' : string,
  'resellerEligibility' : Array<string>,
  'endDate' : bigint,
  'createdAt' : bigint,
  'createdBy' : string,
  'description' : string,
  'fileKeys' : Array<string>,
  'callToAction' : string,
  'promoName' : string,
  'product' : string,
  'startDate' : bigint,
}
export interface PromotionInput {
  'resellerEligibility' : Array<string>,
  'endDate' : bigint,
  'description' : string,
  'fileKeys' : Array<string>,
  'callToAction' : string,
  'promoName' : string,
  'product' : string,
  'startDate' : bigint,
}
export interface QTDFilters {
  'country' : [] | [string],
  'tierName' : [] | [string],
  'productFamily' : [] | [string],
  'quarterKey' : [] | [string],
  'resellerId' : [] | [string],
  'currency' : [] | [string],
  'targetSegment' : [] | [TargetMeasureId],
}
export interface QTDMetrics {
  'dealRegistrationsApproved' : bigint,
  'pipelineClosed' : number,
  'quarterKey' : string,
  'newBusinessRevenue' : number,
  'calculatedAt' : Timestamp,
  'resellerId' : [] | [string],
  'currency' : string,
  'renewalRevenue' : number,
  'dealRegistrationsSubmitted' : bigint,
  'pipelineCreated' : number,
}
export interface QuarterDef {
  'endDate' : string,
  'name' : string,
  'quarterId' : string,
  'startDate' : string,
}
export interface ReadReceipt { 'userId' : string, 'readAt' : bigint }
export type ReassignmentApprovalStatus = { 'Approved' : null } |
  { 'Rejected' : null } |
  { 'Pending' : null };
export interface RenewalRiskScore {
  'accountId' : string,
  'lastAnalyzed' : Timestamp,
  'signals' : Array<RiskSignal>,
  'recommendations' : Array<string>,
  'tier' : RiskTier,
  'score' : bigint,
  'confidence' : bigint,
}
export interface ReportFilters {
  'status' : [] | [string],
  'endDate' : [] | [Timestamp],
  'distributorId' : [] | [string],
  'accountOwnerId' : [] | [string],
  'resellerId' : [] | [string],
  'startDate' : [] | [Timestamp],
}
export interface ResellerInput {
  'emailDomain' : string,
  'primaryAdminEmail' : string,
  'logoKey' : [] | [string],
  'companyName' : string,
  'companyId' : string,
}
export interface ResellerQTDRanking {
  'rank' : bigint,
  'attainmentPercent' : number,
  'resellerId' : string,
  'resellerName' : string,
  'renewalRevenue' : number,
}
export interface ResidentInvitation {
  'id' : string,
  'status' : InvitationStatus,
  'expiresAt' : bigint,
  'createdAt' : bigint,
  'role' : UserRole,
  'invitedBy' : string,
  'email' : string,
  'companyId' : string,
}
export type Result = { 'ok' : Array<string> } |
  { 'err' : AuthError };
export type Result_1 = { 'ok' : SessionToken } |
  { 'err' : AuthError };
export type Result_10 = { 'ok' : DistributorProfile } |
  { 'err' : string };
export type Result_11 = { 'ok' : DealRegistration } |
  { 'err' : string };
export type Result_12 = { 'ok' : Contact } |
  { 'err' : string };
export type Result_13 = { 'ok' : BusinessPlan } |
  { 'err' : string };
export type Result_14 = { 'ok' : Account } |
  { 'err' : string };
export type Result_15 = { 'ok' : UnlockRequest } |
  { 'err' : string };
export type Result_16 = { 'ok' : MfaSetupChallenge } |
  { 'err' : AuthError };
export type Result_17 = { 'ok' : Message } |
  { 'err' : string };
export type Result_18 = { 'ok' : UserProfile } |
  { 'err' : string };
export type Result_19 = { 'ok' : TargetAssignment } |
  { 'err' : string };
export type Result_2 = { 'ok' : null } |
  { 'err' : AuthError };
export type Result_20 = { 'ok' : FiscalYearConfig } |
  { 'err' : string };
export type Result_21 = { 'ok' : SmartQueryResult } |
  { 'err' : string };
export type Result_22 = { 'ok' : NLQueryResult } |
  { 'err' : string };
export type Result_23 = {
    'ok' : {
      'gapAlerts' : Array<EngagementGapAlert>,
      'recommendations' : Array<ForgeAIRecommendation>,
      'riskScores' : Array<RenewalRiskScore>,
    }
  } |
  { 'err' : string };
export type Result_24 = { 'ok' : CreditBalance } |
  { 'err' : string };
export type Result_25 = { 'ok' : ResidentInvitation } |
  { 'err' : string };
export type Result_26 = { 'ok' : string } |
  { 'err' : string };
export type Result_27 = { 'ok' : PasswordResetToken } |
  { 'err' : AuthError };
export type Result_28 = { 'ok' : CompanyProfile } |
  { 'err' : string };
export type Result_29 = { 'ok' : Conversation } |
  { 'err' : string };
export type Result_3 = { 'ok' : null } |
  { 'err' : string };
export type Result_30 = { 'ok' : ConversationThread } |
  { 'err' : string };
export type Result_31 = { 'ok' : Alert } |
  { 'err' : string };
export type Result_4 = { 'ok' : Promotion } |
  { 'err' : string };
export type Result_5 = { 'ok' : PriceList } |
  { 'err' : string };
export type Result_6 = { 'ok' : Note } |
  { 'err' : string };
export type Result_7 = { 'ok' : NewsItem } |
  { 'err' : string };
export type Result_8 = { 'ok' : UserProfileDetail } |
  { 'err' : string };
export type Result_9 = { 'ok' : TargetMeasureConfig } |
  { 'err' : string };
export interface RiskSignal {
  'dataSource' : string,
  'description' : string,
  'severity' : RiskTier,
  'signalType' : string,
}
export type RiskTier = { 'Low' : null } |
  { 'High' : null } |
  { 'Medium' : null } |
  { 'Healthy' : null } |
  { 'Critical' : null };
export interface RoleMapping {
  'providerGroup' : string,
  'channelforgeRole' : string,
}
export interface SSOConfig {
  'metadataUrl' : string,
  'clientId' : string,
  'issuerUrl' : string,
  'allowFallbackPassword' : boolean,
  'provider' : SSOProvider,
  'orgId' : string,
  'roleMapping' : Array<RoleMapping>,
  'enabled' : boolean,
  'updatedAt' : bigint,
  'updatedBy' : string,
  'domainMapping' : Array<string>,
  'forceSso' : boolean,
  'callbackUrl' : string,
  'clientSecret' : string,
}
export type SSOProvider = { 'azure_ad' : null } |
  { 'custom' : null } |
  { 'none' : null } |
  { 'oidc' : null } |
  { 'okta' : null } |
  { 'saml' : null } |
  { 'google_workspace' : null } |
  { 'internet_identity' : null };
export interface SessionToken {
  'token' : string,
  'expiresAt' : bigint,
  'userId' : string,
  'createdAt' : bigint,
  'mfaVerified' : boolean,
  'isPendingMfa' : boolean,
  'companyType' : CompanyType,
  'companyId' : string,
}
export interface SmartQueryFilter {
  'region' : [] | [string],
  'renewalWindowDays' : [] | [bigint],
  'distributorId' : [] | [string],
  'accountManagerId' : [] | [string],
  'resellerId' : [] | [string],
  'maxContractValue' : [] | [bigint],
  'minContractValue' : [] | [bigint],
  'riskLevel' : [] | [string],
  'product' : [] | [string],
}
export interface SmartQueryResult {
  'insights' : Array<string>,
  'queryType' : SmartQueryType,
  'generatedAt' : Timestamp,
  'totalCount' : bigint,
  'summary' : string,
  'items' : Array<SmartQueryResultItem>,
  'filtersApplied' : SmartQueryFilter,
}
export interface SmartQueryResultItem {
  'riskTier' : [] | [RiskTier],
  'distributorName' : [] | [string],
  'lastEngagementDays' : [] | [bigint],
  'entityId' : string,
  'resellerName' : [] | [string],
  'details' : string,
  'entityName' : string,
  'entityType' : string,
  'daysUntilRenewal' : [] | [bigint],
  'riskScore' : [] | [bigint],
}
export type SmartQueryType = { 'CustomersNoActivePipeline' : null } |
  { 'InactiveResellers' : null } |
  { 'AccountsNoEngagement' : null } |
  { 'HighRiskRenewals' : null } |
  { 'ContractsMissingPlans' : null } |
  { 'StalledApprovals' : null } |
  { 'DecliningEngagement' : null } |
  { 'HighGrowthOpportunities' : null } |
  { 'TopPerformingDistributors' : null } |
  { 'PendingDRsOver14Days' : null } |
  { 'ResellersBelowTarget' : null } |
  { 'RenewalsExpiringNextMonth' : null };
export interface TargetAssignment {
  'periodType' : TargetPeriodType,
  'assignedAt' : Timestamp,
  'assignedBy' : string,
  'assignmentScope' : TargetScope,
  'periodKey' : string,
  'assignmentId' : string,
  'vendorId' : string,
  'targetValue' : number,
  'measureId' : TargetMeasureId,
}
export interface TargetAssignmentInput {
  'periodType' : TargetPeriodType,
  'assignmentScope' : TargetScope,
  'periodKey' : string,
  'targetValue' : number,
  'measureId' : TargetMeasureId,
}
export type TargetCalculationType = { 'Weighted' : null } |
  { 'Count' : null } |
  { 'Percentage' : null } |
  { 'Revenue' : null };
export interface TargetMeasure {
  'calculationType' : TargetCalculationType,
  'defaultName' : string,
  'customName' : [] | [string],
  'measureId' : TargetMeasureId,
}
export interface TargetMeasureConfig {
  'measures' : Array<TargetMeasure>,
  'updatedAt' : Timestamp,
  'updatedBy' : string,
  'vendorId' : string,
}
export type TargetMeasureId = { 'Measure1' : null } |
  { 'Measure2' : null } |
  { 'Measure3' : null } |
  { 'Measure4' : null } |
  { 'Measure5' : null };
export type TargetPeriodType = { 'Quarterly' : null } |
  { 'Annual' : null };
export type TargetScope = { 'ByDistributor' : string } |
  { 'ByTier' : string } |
  { 'ByUser' : string } |
  { 'ByCountry' : string } |
  { 'ByReseller' : string } |
  { 'AllResellers' : null } |
  { 'ByProductFamily' : string };
export interface TierAssignment {
  'assignedAt' : Timestamp,
  'assignedBy' : Principal,
  'tier' : PartnerTier,
  'resellerId' : string,
}
export interface TierConfig {
  'permissions' : Array<TierPermission>,
  'tier' : PartnerTier,
  'updatedAt' : Timestamp,
  'updatedBy' : Principal,
  'maxSecondaryAdmins' : bigint,
}
export interface TierOverride {
  'permission' : TierPermission,
  'overriddenAt' : Timestamp,
  'overriddenBy' : Principal,
  'granted' : boolean,
  'resellerId' : string,
  'reason' : string,
}
export type TierPermission = { 'MDFRequests' : null } |
  { 'ExportPermissions' : null } |
  { 'PricingDiscounts' : null } |
  { 'RenewalVisibilityDepth' : null } |
  { 'CustomerAnalytics' : null } |
  { 'StrategicAccountInsights' : null } |
  { 'APIAccess' : null } |
  { 'AIRecommendations' : null } |
  { 'ForecastVisibility' : null } |
  { 'PromotionsVisibility' : null } |
  { 'PipelineReporting' : null } |
  { 'AdvancedDashboards' : null } |
  { 'DealRegistrations' : null } |
  { 'SecondaryAdminAccess' : null };
export type Timestamp = bigint;
export interface UnlockRequest {
  'ruleName' : string,
  'requestingAdminName' : string,
  'status' : UnlockRequestStatus,
  'requestingOrgId' : string,
  'requestId' : string,
  'requestingAdminId' : Principal,
  'ruleId' : NotificationRuleId,
  'createdAt' : Timestamp,
  'lockSource' : LockSource,
  'targetOrgId' : string,
  'resolvedAt' : [] | [Timestamp],
  'resolvedBy' : [] | [Principal],
  'reason' : string,
}
export type UnlockRequestStatus = { 'Approved' : null } |
  { 'Declined' : null } |
  { 'Pending' : null };
export interface UsageEvent {
  'orgId' : string,
  'storageCost' : bigint,
  'userId' : string,
  'actionType' : string,
  'aiCost' : bigint,
  'timestamp' : bigint,
  'computeCost' : bigint,
}
export interface UserProfile {
  'id' : string,
  'isPrimaryAdmin' : boolean,
  'permissions' : Array<string>,
  'createdAt' : bigint,
  'role' : UserRole,
  'fullName' : string,
  'email' : string,
  'companyId' : string,
}
export interface UserProfileDetail {
  'region' : [] | [string],
  'timezone' : [] | [string],
  'userRole' : UserRole,
  'displayName' : string,
  'userId' : string,
  'createdAt' : bigint,
  'photoUrl' : [] | [string],
  'roleDescription' : [] | [string],
  'email' : string,
  'linkedInUrl' : [] | [string],
  'updatedAt' : bigint,
  'jobTitle' : string,
  'companyType' : CompanyType,
  'visibilityScope' : ProfileVisibilityScope,
  'companyId' : string,
}
export interface UserProfileDetailInput {
  'region' : [] | [string],
  'timezone' : [] | [string],
  'displayName' : string,
  'photoUrl' : [] | [string],
  'roleDescription' : [] | [string],
  'linkedInUrl' : [] | [string],
  'jobTitle' : string,
  'visibilityScope' : ProfileVisibilityScope,
}
export interface UserProfileInput {
  'isPrimaryAdmin' : boolean,
  'permissions' : Array<string>,
  'role' : UserRole,
  'fullName' : string,
  'email' : string,
  'companyId' : string,
}
export type UserRole = { 'DistributorSecondaryAdmin' : null } |
  { 'ResellerSalesUser' : null } |
  { 'ResellerPrimaryAdmin' : null } |
  { 'VendorSecondaryAdmin' : null } |
  { 'VendorAdmin' : null } |
  { 'DistributorPrimaryAdmin' : null } |
  { 'DistributorSalesUser' : null } |
  { 'ResellerAdmin' : null } |
  { 'VendorPrimaryAdmin' : null } |
  { 'ReadOnlyViewer' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VisibilityCondition {
  'value' : string,
  'conditionType' : VisibilityConditionType,
}
export type VisibilityConditionType = { 'ByRole' : null } |
  { 'ByOrgType' : null } |
  { 'ByAccountType' : null } |
  { 'ByDepartment' : null } |
  { 'ByMarketSegment' : null } |
  { 'ByTerritory' : null };
export type VisibilityOperator = { 'Or' : null } |
  { 'And' : null };
export interface VisibilityRule {
  'id' : string,
  'ruleType' : VisibilityRuleType,
  'orgId' : string,
  'createdAt' : bigint,
  'isActive' : boolean,
  'updatedAt' : bigint,
  'conditions' : Array<VisibilityRuleCondition>,
  'objectType' : CustomFieldObjectType,
}
export type VisibilityRuleAction = { 'Hide' : null } |
  { 'Show' : null };
export interface VisibilityRuleCondition {
  'conditionOperator' : ConditionOperator,
  'conditionField' : string,
  'conditionValue' : string,
}
export interface VisibilityRuleInput {
  'ruleType' : VisibilityRuleType,
  'isActive' : boolean,
  'conditions' : Array<VisibilityRuleCondition>,
  'objectType' : CustomFieldObjectType,
}
export type VisibilityRuleType = { 'allow' : null } |
  { 'deny' : null };
export interface VisibilityRule__1 {
  'id' : string,
  'action' : VisibilityRuleAction,
  'operator' : VisibilityOperator,
  'targetType' : VisibilityTargetType,
  'conditions' : Array<VisibilityCondition>,
  'targetId' : string,
}
export type VisibilityTargetType = { 'Tab' : null } |
  { 'Section' : null } |
  { 'Field' : null };
export interface WidgetConfig {
  'title' : string,
  'widgetId' : string,
  'refreshIntervalSecs' : [] | [bigint],
  'posX' : bigint,
  'posY' : bigint,
  'size' : WidgetSize,
  'roleFilter' : Array<string>,
  'widgetType' : WidgetType,
  'aiSummaryEnabled' : boolean,
  'accountFilter' : [] | [string],
  'dateRange' : [] | [string],
  'customConfig' : string,
  'isPinned' : boolean,
  'deptFilter' : Array<string>,
  'territoryFilter' : [] | [string],
}
export type WidgetSize = { 'Large' : null } |
  { 'Small' : null } |
  { 'Medium' : null } |
  { 'Tall' : null } |
  { 'Wide' : null } |
  { 'FullWidth' : null };
export type WidgetType = { 'PipelineBoard' : null } |
  { 'MessagingWidget' : null } |
  { 'SlaTracking' : null } |
  { 'OpportunitySummary' : null } |
  { 'AiInsights' : null } |
  { 'DistributorPerformance' : null } |
  { 'MdfTracking' : null } |
  { 'TerritoryPerformance' : null } |
  { 'AccountHealth' : null } |
  { 'Custom' : null } |
  { 'Forecasting' : null } |
  { 'LineGraph' : null } |
  { 'ResellerPerformance' : null } |
  { 'KpiCard' : null } |
  { 'ComputeStorage' : null } |
  { 'RenewalTracker' : null } |
  { 'OperationalAlerts' : null } |
  { 'AiUsage' : null } |
  { 'ActivityFeed' : null } |
  { 'BarChart' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'activateDistributor' : ActorMethod<[string], Result_10>,
  'activateReseller' : ActorMethod<[string], Result_28>,
  'activateUser' : ActorMethod<[string], Result_2>,
  'addAccountSite' : ActorMethod<[string, AccountSite], Result_14>,
  'addDistributorToAccount' : ActorMethod<[string, string, string], Result_14>,
  'addResellerToDistributor' : ActorMethod<[string, string], Result_10>,
  'addTierOverride' : ActorMethod<
    [string, TierPermission, boolean, string],
    boolean
  >,
  'addTopUp' : ActorMethod<[string, CreditTopUp], Result_24>,
  'addVendorRelationship' : ActorMethod<[string, string], Result_10>,
  'aiAddProvider' : ActorMethod<[AIProvider, AIProviderConfig], boolean>,
  'aiCreateChatSession' : ActorMethod<
    [string, [] | [string], [] | [string]],
    ForgeAIChatSession
  >,
  'aiDeleteProvider' : ActorMethod<[string], boolean>,
  'aiDisableProvider' : ActorMethod<[string], boolean>,
  'aiEnableProvider' : ActorMethod<[string], boolean>,
  'aiGetChatSession' : ActorMethod<[string], [] | [ForgeAIChatSession]>,
  'aiGetProvider' : ActorMethod<[string], [] | [AIProvider]>,
  'aiGetProviderConfig' : ActorMethod<[string], [] | [AIProviderConfig]>,
  'aiGrantAccess' : ActorMethod<[AIAccessRule], boolean>,
  'aiListAccessRules' : ActorMethod<[string], Array<AIAccessRule>>,
  'aiListAuditLog' : ActorMethod<[string, bigint], Array<AIAuditEntry>>,
  'aiListChatSessions' : ActorMethod<[], Array<ForgeAIChatSession>>,
  'aiListProviders' : ActorMethod<[string], Array<AIProvider>>,
  'aiResolveProviderForCaller' : ActorMethod<
    [string, string, [] | [string]],
    [] | [string]
  >,
  'aiRevokeAccess' : ActorMethod<[string], boolean>,
  'aiSendChatMessage' : ActorMethod<[string, string], ChatMessage>,
  'aiTestProviderConnection' : ActorMethod<[string], string>,
  'aiUpdateApiKey' : ActorMethod<[string, string], boolean>,
  'aiUpdateProviderConfig' : ActorMethod<[AIProviderConfig], boolean>,
  'archiveCustomFieldDef' : ActorMethod<[string], boolean>,
  'archiveOpportunity' : ActorMethod<[string], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'assignTierToReseller' : ActorMethod<[string, PartnerTier], boolean>,
  'bulkCreateAccounts' : ActorMethod<[Array<AccountInput>], BulkImportResult>,
  'bulkCreateContacts' : ActorMethod<[Array<ContactInput>], BulkImportResult>,
  'bulkSetCustomFieldValues' : ActorMethod<
    [Array<CustomFieldValueInput>],
    CustomFieldBulkValidationResult
  >,
  'cancelInvitation' : ActorMethod<[string], Result_3>,
  'cancelMdfRequest' : ActorMethod<[string], boolean>,
  'checkAccountDuplicate' : ActorMethod<[string, string], DuplicateCheckResult>,
  'checkVisibility' : ActorMethod<
    [string, CustomFieldObjectType, string, [] | [string]],
    boolean
  >,
  'cloneDashboardLayout' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'cloneTierPermissions' : ActorMethod<[PartnerTier, PartnerTier], boolean>,
  'completeSetup' : ActorMethod<[string], Result_28>,
  'createAccount' : ActorMethod<[AccountInput], Result_14>,
  'createAlert' : ActorMethod<[AlertInput], Result_31>,
  'createBusinessPlan' : ActorMethod<[BusinessPlanInput], Result_13>,
  'createCompanyProfile' : ActorMethod<[CompanyProfileInput], Result_28>,
  'createContact' : ActorMethod<[ContactInput], Result_12>,
  'createCustomFieldDef' : ActorMethod<[CustomFieldDefInput], CustomFieldDef>,
  'createDealRegistration' : ActorMethod<[DealRegistrationInput], Result_11>,
  'createDirectMessage' : ActorMethod<
    [string, string, Array<string>],
    Result_30
  >,
  'createDistributor' : ActorMethod<[string, DistributorInput], Result_10>,
  'createGroupConversation' : ActorMethod<
    [Array<string>, string, [] | [string]],
    Result_29
  >,
  'createMarketingActivity' : ActorMethod<
    [MarketingActivityInput],
    MarketingActivity
  >,
  'createMdfRequest' : ActorMethod<[string, MdfRequestInput], MdfRequest>,
  'createNewsItem' : ActorMethod<[NewsItemInput], Result_7>,
  'createNote' : ActorMethod<[NoteInput], Result_6>,
  'createOpportunity' : ActorMethod<[OpportunityInput], Opportunity>,
  'createPriceList' : ActorMethod<[PriceListInput], Result_5>,
  'createPromotion' : ActorMethod<[PromotionInput], Result_4>,
  'createReseller' : ActorMethod<[string, ResellerInput], Result_28>,
  'createVisibilityRule' : ActorMethod<
    [string, VisibilityRuleInput],
    VisibilityRule
  >,
  'deactivateReseller' : ActorMethod<[string], Result_28>,
  'deactivateUser' : ActorMethod<[string], Result_2>,
  'decideMdfRequest' : ActorMethod<
    [string, MdfRequestDecisionInput],
    [] | [MdfRequest]
  >,
  'deleteAccount' : ActorMethod<[string], Result_3>,
  'deleteAccountLayout' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteContact' : ActorMethod<[string], Result_3>,
  'deleteDealRegistration' : ActorMethod<[string], Result_3>,
  'deleteNewsItem' : ActorMethod<[string], Result_3>,
  'deleteNote' : ActorMethod<[string], Result_3>,
  'deleteNotification' : ActorMethod<[string], Result_3>,
  'deletePriceList' : ActorMethod<[string], Result_3>,
  'deletePromotion' : ActorMethod<[string], Result_3>,
  'deleteTargetAssignment' : ActorMethod<[string], Result_3>,
  'deleteVisibilityRule' : ActorMethod<[string], boolean>,
  'dismissAlert' : ActorMethod<[string], Result_3>,
  'dismissForgeAIRecommendation' : ActorMethod<[string], Result_3>,
  'estimateDaysRemaining' : ActorMethod<[string], bigint>,
  'estimateMonthlyUsage' : ActorMethod<[string], bigint>,
  'forgotPassword' : ActorMethod<[string, CompanyType, string], Result_27>,
  'generateCustomerId' : ActorMethod<
    [CustomerIdGenerateRequest],
    CustomerIdValidationResult
  >,
  'getAccount' : ActorMethod<[string], [] | [Account]>,
  'getAccountLayouts' : ActorMethod<[], Array<AccountLayout>>,
  'getAccountReassignmentLog' : ActorMethod<
    [string],
    Array<AccountReassignmentEntry>
  >,
  'getAccountsByDistributor' : ActorMethod<[string], Array<Account>>,
  'getAccountsByReseller' : ActorMethod<[string], Array<Account>>,
  'getActiveResetTokens' : ActorMethod<[string], Array<ActiveResetTokenView>>,
  'getAllAccounts' : ActorMethod<[], Array<Account>>,
  'getAllBusinessPlans' : ActorMethod<[], Array<BusinessPlan>>,
  'getAllDealRegistrations' : ActorMethod<[], Array<DealRegistration>>,
  'getAllNews' : ActorMethod<[], Array<NewsItem>>,
  'getAllPriceLists' : ActorMethod<[], Array<PriceList>>,
  'getAllPromotions' : ActorMethod<[], Array<Promotion>>,
  'getAuditLog' : ActorMethod<[bigint], Array<AuditEntry>>,
  'getAuthSettings' : ActorMethod<[string], AuthSettings>,
  'getBusinessPlan' : ActorMethod<[string], [] | [BusinessPlan]>,
  'getBusinessPlansByPartner' : ActorMethod<[string], Array<BusinessPlan>>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getCompanyProfile' : ActorMethod<[string], [] | [CompanyProfile]>,
  'getContact' : ActorMethod<[string], [] | [Contact]>,
  'getContactsByAccount' : ActorMethod<[string], Array<Contact>>,
  'getConversationMessages' : ActorMethod<
    [string, bigint, bigint],
    Array<Message>
  >,
  'getConversationThread' : ActorMethod<[string], [] | [ConversationThread]>,
  'getCreditBalance' : ActorMethod<[string], CreditBalance>,
  'getCreditPackages' : ActorMethod<[], Array<CreditPackage>>,
  'getCurrentQuarter' : ActorMethod<[], [] | [CurrentQuarterResult]>,
  'getCustomFieldDef' : ActorMethod<[string], [] | [CustomFieldDef]>,
  'getCustomFieldValues' : ActorMethod<
    [string, CustomFieldObjectType],
    Array<CustomFieldValue>
  >,
  'getCustomerIdAuditLog' : ActorMethod<[string], Array<CustomerIdAuditEntry>>,
  'getCustomerIdFormatRule' : ActorMethod<
    [string],
    [] | [CustomerIdFormatRule]
  >,
  'getDashboardLayouts' : ActorMethod<[], Array<DashboardLayout>>,
  'getDashboardTemplates' : ActorMethod<[], Array<DashboardLayout>>,
  'getDealRegistration' : ActorMethod<[string], [] | [DealRegistration]>,
  'getDealRegistrationReport' : ActorMethod<
    [ReportFilters],
    Array<DealRegistration>
  >,
  'getDealRegistrationsByReseller' : ActorMethod<
    [string],
    Array<DealRegistration>
  >,
  'getDistributor' : ActorMethod<[string], [] | [DistributorProfile]>,
  'getDistributorCustomerAccounts' : ActorMethod<[string], Array<Account>>,
  'getDistributorResellers' : ActorMethod<[string], Array<string>>,
  'getDuplicateDRQueue' : ActorMethod<[], Array<DuplicateDRRecord>>,
  'getEffectiveTierPermissions' : ActorMethod<[string], Array<TierPermission>>,
  'getFailedLoginHistory' : ActorMethod<
    [string, bigint],
    Array<FailedLoginEvent>
  >,
  'getFiscalYearConfig' : ActorMethod<[], [] | [FiscalYearConfig]>,
  'getForexConfig' : ActorMethod<[], ForexConfig>,
  'getForgeAIAuditLog' : ActorMethod<[bigint], Array<ForgeAIAuditEntry>>,
  'getForgeAIRecommendations' : ActorMethod<[], Array<ForgeAIRecommendation>>,
  'getForgeAISettings' : ActorMethod<[], ForgeAISettings>,
  'getGapNotificationConfig' : ActorMethod<[], GapNotificationConfig>,
  'getHighRiskAccounts' : ActorMethod<[], Array<Account>>,
  'getInvitations' : ActorMethod<[string], Array<ResidentInvitation>>,
  'getLatestRate' : ActorMethod<
    [Currency, Currency],
    [] | [ExchangeRateSnapshot]
  >,
  'getLayoutAuditLog' : ActorMethod<[], Array<LayoutAuditEntry>>,
  'getLayoutForUser' : ActorMethod<
    [string, string, string],
    [] | [AccountLayout]
  >,
  'getLayoutPermissions' : ActorMethod<[string], [] | [LayoutPermissions]>,
  'getLockedAccounts' : ActorMethod<[string], Array<LockedAccountInfo>>,
  'getMarketingActivity' : ActorMethod<[string], [] | [MarketingActivity]>,
  'getMdfRequest' : ActorMethod<[string], [] | [MdfRequest]>,
  'getMeasureConfig' : ActorMethod<[], TargetMeasureConfig>,
  'getMyAlerts' : ActorMethod<[], Array<Alert>>,
  'getMyCompany' : ActorMethod<[], [] | [CompanyProfile]>,
  'getMyNotifications' : ActorMethod<[], Array<InAppNotification>>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfileDetail]>,
  'getMyUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getNewsItem' : ActorMethod<[string], [] | [NewsItem]>,
  'getNextAvailableResellerId' : ActorMethod<[string, string], Result_26>,
  'getNotesByAccount' : ActorMethod<[string], Array<Note>>,
  'getOpportunity' : ActorMethod<[string], [] | [Opportunity]>,
  'getOrgForgeAIAlertSettings' : ActorMethod<[string], OrgForgeAIAlertSettings>,
  'getOrgNotificationRules' : ActorMethod<[string], Array<NotificationRule>>,
  'getOrgVisibilityConfig' : ActorMethod<[string], OrgVisibilityConfig>,
  'getOverridesForReseller' : ActorMethod<[string], Array<TierOverride>>,
  'getPartnerRankings' : ActorMethod<[string], Array<ResellerQTDRanking>>,
  'getPipelineReport' : ActorMethod<[ReportFilters], Array<DealRegistration>>,
  'getPriceList' : ActorMethod<[string], [] | [PriceList]>,
  'getPromotion' : ActorMethod<[string], [] | [Promotion]>,
  'getPromotionsForPartner' : ActorMethod<[string], Array<Promotion>>,
  'getQTDMetrics' : ActorMethod<[QTDFilters], QTDMetrics>,
  'getRateAtDate' : ActorMethod<
    [Currency, Currency, Timestamp],
    [] | [ExchangeRateSnapshot]
  >,
  'getRenewalReport' : ActorMethod<[ReportFilters], Array<Account>>,
  'getRenewalsDue' : ActorMethod<[bigint], Array<Account>>,
  'getResellerTier' : ActorMethod<[string], [] | [TierAssignment]>,
  'getResellersForVendor' : ActorMethod<[string], Array<CompanyProfile>>,
  'getSsoConfig' : ActorMethod<[string], [] | [SSOConfig]>,
  'getTargetAssignments' : ActorMethod<
    [[] | [TargetMeasureId], [] | [string]],
    Array<TargetAssignment>
  >,
  'getTierConfigs' : ActorMethod<[], Array<TierConfig>>,
  'getTopUpHistory' : ActorMethod<[string], Array<CreditTopUp>>,
  'getUnlockRequests' : ActorMethod<[string], Array<UnlockRequest>>,
  'getUnreadNotificationCount' : ActorMethod<[], bigint>,
  'getUsageHistory' : ActorMethod<[string], Array<UsageEvent>>,
  'getUsageTrend' : ActorMethod<[string], string>,
  'getUserProfile' : ActorMethod<[string], [] | [UserProfileDetail]>,
  'getUsersByCompany' : ActorMethod<[string], Array<UserProfile>>,
  'getVisibilityRulesForLayout' : ActorMethod<
    [string],
    Array<VisibilityRule__1>
  >,
  'getVisibleNews' : ActorMethod<[string, string], Array<NewsItem>>,
  'grantForgeAIAlertsPermission' : ActorMethod<[string, Principal], Result_3>,
  'initUserAuthState' : ActorMethod<[string, string], undefined>,
  'inviteUser' : ActorMethod<[InviteUserInput], Result_25>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCustomerIdDuplicate' : ActorMethod<[string, string], boolean>,
  'listCustomFieldDefs' : ActorMethod<
    [CustomFieldObjectType],
    Array<CustomFieldDef>
  >,
  'listDistributors' : ActorMethod<[], Array<DistributorProfile>>,
  'listDistributorsByVendor' : ActorMethod<[string], Array<DistributorProfile>>,
  'listMarketingActivities' : ActorMethod<
    [
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [MarketingActivityType],
      [] | [MarketingActivityStatus],
    ],
    Array<MarketingActivity>
  >,
  'listMarketingActivitiesForCaller' : ActorMethod<
    [[] | [string], string, string, [] | [string], [] | [string]],
    Array<MarketingActivity>
  >,
  'listMdfRequests' : ActorMethod<
    [[] | [string], [] | [string], [] | [MdfRequestStatus], [] | [bigint]],
    Array<MdfRequest>
  >,
  'listMdfRequestsForCaller' : ActorMethod<
    [[] | [string], string, string, [] | [string], [] | [string]],
    Array<MdfRequest>
  >,
  'listMyConversations' : ActorMethod<[], Array<Conversation>>,
  'listOpportunities' : ActorMethod<
    [
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [OpportunityStage],
      boolean,
    ],
    Array<Opportunity>
  >,
  'listOpportunitiesForCaller' : ActorMethod<
    [[] | [string], string, string, [] | [string], [] | [string]],
    Array<Opportunity>
  >,
  'listVisibilityRules' : ActorMethod<[string, boolean], Array<VisibilityRule>>,
  'listWorkspaceProfiles' : ActorMethod<[string], Array<UserProfileDetail>>,
  'logAccountReassignment' : ActorMethod<
    [string, AccountReassignmentEntry],
    Result_3
  >,
  'loginWithEmailPassword' : ActorMethod<
    [string, string, CompanyType, string],
    Result_1
  >,
  'logout' : ActorMethod<[string], undefined>,
  'mapCsvHeadersToCustomFields' : ActorMethod<
    [CustomFieldObjectType, Array<string>],
    Array<[string, [] | [string]]>
  >,
  'markAlertRead' : ActorMethod<[string], Result_3>,
  'markMdfRequestPaid' : ActorMethod<[string], boolean>,
  'markMessagesRead' : ActorMethod<[string, string], Result_3>,
  'markNotificationRead' : ActorMethod<[string], Result_3>,
  'reassignAccountReseller' : ActorMethod<[string, string], Result_14>,
  'recordMarketingActivityRoi' : ActorMethod<[string, bigint], boolean>,
  'recordUsageEvent' : ActorMethod<[UsageEvent], Result_24>,
  'regenerateRecoveryCodes' : ActorMethod<[string], Result>,
  'registerCustomerId' : ActorMethod<[string, string, string], boolean>,
  'removeAccountSite' : ActorMethod<[string, string], Result_14>,
  'removeDistributorFromAccount' : ActorMethod<[string, string], Result_14>,
  'resetMfaForUser' : ActorMethod<[string], Result_2>,
  'resetPasswordWithToken' : ActorMethod<[string, string, string], Result_2>,
  'resolveUnlockRequest' : ActorMethod<[string, boolean], Result_3>,
  'reviewDuplicateDR' : ActorMethod<
    [string, DuplicateDRStatus, string],
    boolean
  >,
  'revokeAllSessions' : ActorMethod<[string], undefined>,
  'revokeForgeAIAlertsPermission' : ActorMethod<[string, Principal], Result_3>,
  'revokePasswordResetToken' : ActorMethod<[string], Result_2>,
  'runForgeAIAnalysis' : ActorMethod<[], Result_23>,
  'runNLQuery' : ActorMethod<[string], Result_22>,
  'runSmartQuery' : ActorMethod<[SmartQueryType, SmartQueryFilter], Result_21>,
  'saveAccountLayout' : ActorMethod<
    [AccountLayout],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'saveDashboardLayout' : ActorMethod<
    [DashboardLayout],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'saveFiscalYearConfig' : ActorMethod<[FiscalYearConfigInput], Result_20>,
  'saveTargetAssignment' : ActorMethod<[TargetAssignmentInput], Result_19>,
  'saveUserProfile' : ActorMethod<[UserProfileInput], Result_18>,
  'saveVisibilityRule' : ActorMethod<
    [VisibilityRule__1],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'searchCustomFieldValues' : ActorMethod<
    [CustomFieldObjectType, string, string],
    Array<string>
  >,
  'searchMyMessages' : ActorMethod<[string], Array<Message>>,
  'sendMessageToConversation' : ActorMethod<
    [string, string, Array<string>],
    Result_17
  >,
  'setCustomFieldValue' : ActorMethod<
    [CustomFieldValueInput],
    CustomFieldValidationResult
  >,
  'setPassword' : ActorMethod<[string, string], Result_2>,
  'setupMfa' : ActorMethod<[string], Result_16>,
  'shareMaskAuthority' : ActorMethod<[string, string], boolean>,
  'storeExchangeRates' : ActorMethod<[Array<ExchangeRateSnapshot>], undefined>,
  'submitUnlockRequest' : ActorMethod<
    [string, string, string, string, string, LockSource, string, Principal],
    Result_15
  >,
  'suspendDistributor' : ActorMethod<[string], Result_10>,
  'unlockUserAccount' : ActorMethod<[string, string], Result_2>,
  'updateAccount' : ActorMethod<[string, AccountInput], Result_14>,
  'updateAccountSite' : ActorMethod<[string, AccountSite], Result_14>,
  'updateAuthSettings' : ActorMethod<[string, AuthSettings], Result_2>,
  'updateBusinessPlan' : ActorMethod<[string, BusinessPlanInput], Result_13>,
  'updateBusinessPlanActivity' : ActorMethod<
    [string, string, ActivityStatus],
    Result_13
  >,
  'updateContact' : ActorMethod<[string, ContactInput], Result_12>,
  'updateCustomFieldDef' : ActorMethod<
    [string, CustomFieldDefInput],
    [] | [CustomFieldDef]
  >,
  'updateDealRegistration' : ActorMethod<
    [string, DealRegistrationInput],
    Result_11
  >,
  'updateDealStatus' : ActorMethod<[string, DealStatus], Result_11>,
  'updateDistributor' : ActorMethod<[string, DistributorInput], Result_10>,
  'updateForexConfig' : ActorMethod<[ForexConfig], boolean>,
  'updateForgeAIAlertConfig' : ActorMethod<
    [string, ForgeAIAlertConfig],
    Result_3
  >,
  'updateForgeAISettings' : ActorMethod<[ForgeAISettings], Result_3>,
  'updateGapNotificationConfig' : ActorMethod<
    [GapNotificationConfig],
    Result_3
  >,
  'updateLayoutPermissions' : ActorMethod<
    [string, LayoutPermissions],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateMarketingActivity' : ActorMethod<
    [string, MarketingActivityUpdateInput],
    [] | [MarketingActivity]
  >,
  'updateMeasureName' : ActorMethod<[TargetMeasureId, string], Result_9>,
  'updateMyProfile' : ActorMethod<[UserProfileDetailInput], Result_8>,
  'updateNewsItem' : ActorMethod<[string, NewsItemInput], Result_7>,
  'updateNote' : ActorMethod<[string, string], Result_6>,
  'updateOpportunity' : ActorMethod<
    [string, OpportunityUpdateInput],
    [] | [Opportunity]
  >,
  'updateOrgVisibilityConfig' : ActorMethod<
    [string, OrgVisibilityConfigInput],
    OrgVisibilityConfig
  >,
  'updatePriceList' : ActorMethod<[string, PriceListInput], Result_5>,
  'updatePromotion' : ActorMethod<[string, PromotionInput], Result_4>,
  'updateSecondaryAdminPermissions' : ActorMethod<
    [string, Array<string>],
    Result_3
  >,
  'updateSsoConfig' : ActorMethod<[string, SSOConfig], Result_2>,
  'updateTierPermissions' : ActorMethod<
    [PartnerTier, Array<TierPermission>, bigint],
    boolean
  >,
  'updateVisibilityRule' : ActorMethod<
    [string, VisibilityRuleInput],
    [] | [VisibilityRule]
  >,
  'upsertCustomerIdFormatRule' : ActorMethod<
    [string, CustomerIdFormatRuleInput],
    CustomerIdFormatRule
  >,
  'validateCustomFieldValues' : ActorMethod<
    [Array<CustomFieldValueInput>],
    CustomFieldBulkValidationResult
  >,
  'validateCustomerId' : ActorMethod<
    [string, string],
    CustomerIdValidationResult
  >,
  'validateMfaToken' : ActorMethod<[string, string, string], Result_1>,
  'validateSession' : ActorMethod<[string], Result_1>,
  'verifyMfaEnrollment' : ActorMethod<[string, string], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];